name: PR Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install cookiecutter
      run: pip install cookiecutter

    - name: Create project from template
      run: cookiecutter . --no-input

    - name: Open Scala Project
      run: cd scala-rest-api-http4s

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
        
    - name: Run tests
      run: sbt test
